title: filtered-point-process
description: A Python package for modeling and analyzing filtered point processes capturing electrophysiological field potentials.

theme: just-the-docs

url: https://stephen-lab-bu.github.io/filtered-point-process/

# Configure navigation
nav:
  - title: Home
    url: /
  - title: Explanations
    url: /Explanations/

search_enabled: true


