name: filtered-point-process
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - ipykernel
  - scipy
  - pip
  - pytest
  - pip:
    - black
    - pre-commit
    - numdifftools
    - nitime
