name: filtered-point-process
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - ipykernel
  - statsmodels
  - scipy
  - pip
  - pytest
  - pip:
    - black
    - "black[jupyter]"
    - pre-commit
    - numdifftools
    - nitime
    - spectral_connectivity
