name: Test Installation from Source

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          channels: conda-forge
          auto-update-conda: false
          auto-activate-base: false

      - name: Install Mamba into base
        run: conda install -n base -c conda-forge mamba

      - name: Create environment from environment.yml
        run: mamba env create -f environment.yml

      - name: Install package from GitHub
        run: |
          conda run -n filtered-point-process python -m pip install git+https://github.com/Stephen-Lab-BU/filtered-point-process.git
          # Verify import works
          conda run -n filtered-point-process python -c "import filtered_point_process"
          echo "Success: The package installed and can be imported."
