name: Test Installation from Source

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        # This action sets up a Miniconda installation so we can run conda/mamba commands.
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: base
          channels: conda-forge
          python-version: 3.9
          auto-update-conda: true
          use-mamba: false

      - name: Install Mamba and create environment
        run: |
          conda install mamba -n base -c conda-forge
          mamba env create -f environment.yml 

      - name: Activate environment and install package from GitHub
        run: |
          conda activate filtered-point-process
          # Now run the final step from your instructions:
          python -m pip install git+https://github.com/Stephen-Lab-BU/filtered-point-process.git
          # Verify it installed and can be imported:
          python -c "import filtered_point_process"
          echo "Success! The package was installed and can be imported."
